sudo: false
language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm
    - nightly

matrix:
    allow_failures:
        - php: nightly

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-text